mutation CREATE_POST($media: [Upload!]) {
  createPost(postInput: {type: "image", title: "thisis image", media: $media}) {
    id
    title
    type
    media {
      id
      path
    }
  }
}


query GetUserPosts($userId: ID!, $offset: Int!, $limit: Int!, $postType: String!) {
  getUserPosts(userId: $userId, offset: $offset, limit: $limit, postType: $postType) {
    id  
    type 
    likes
    liked
    media {
        id path 
    }
  }
}