mutation Replay($replayInput: ReplayInput!) {
  replay(replayInput: $replayInput) {
    id 
  }
}

query GetCommentReplays($commentId: ID!, $offset: Int!, $limit: Int!) {
  getCommentReplays(commentId: $commentId , offset: $offset , limit: $limit) {
    id
    replay
    mediaId
    userId
    user {
       name lastname
    }
  }
}