mutation ($media: Upload!) {
    createStory(storyInput: {media: $media}) {
      id
      user {
        id
        name
        lastname
      }
      media {
        path
      }
    }
  }
  


  query GetStories {
  getStories {
    id 
    name
    lastname
    stories {
      id
      media {
        id
        path
      }
    liked
      createdAt
    }
  }
}